# paramètres de diffusion
num_timesteps: 1000
beta_start: 0.0001
beta_end: 0.02

# paramètres du modèle
im_channels: 1
im_size: 28

# paramètres d'entraînement
task_name: 'default'
batch_size: 64
num_epochs: 15
num_samples: 1
num_grid_rows: 10
lr: 0.0001
ckpt_name: 'ddpm_ckpt.pth'

